In [32]:
import numpy as np
import pandas as pd

### Series

In [33]:
labels = ['a', 'b', 'c']

arr = np.array([10, 20, 30])

d = {
    'a':10, 
    'b':20, 
    'c':30
}

In [34]:
series = pd.Series(data=arr, index=labels)
series

a    10
b    20
c    30
dtype: int64

In [35]:
ser = pd.Series(d)
ser

a    10
b    20
c    30
dtype: int64

## Dataframes

In [36]:
np.random.seed(42)
randoms = np.random.randn(5,4)
randoms

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [37]:
rows = ['a', 'b', 'c', 'd', 'e']
columns = ['w', 'x', 'y', 'z']

In [38]:
df = pd.DataFrame(data=randoms, index=rows, columns=columns)
df

          w         x         y         z
a  0.496714 -0.138264  0.647689  1.523030
b -0.234153 -0.234137  1.579213  0.767435
c -0.469474  0.542560 -0.463418 -0.465730
d  0.241962 -1.913280 -1.724918 -0.562288
e -1.012831  0.314247 -0.908024 -1.412304

In [39]:
df[['x', 'y']]

          x         y
a -0.138264  0.647689
b -0.234137  1.579213
c  0.542560 -0.463418
d -1.913280 -1.724918
e  0.314247 -0.908024

In [40]:
# create a new column
df['new'] = df['w'] + df['y']
df

          w         x         y         z       new
a  0.496714 -0.138264  0.647689  1.523030  1.144403
b -0.234153 -0.234137  1.579213  0.767435  1.345059
c -0.469474  0.542560 -0.463418 -0.465730 -0.932892
d  0.241962 -1.913280 -1.724918 -0.562288 -1.482956
e -1.012831  0.314247 -0.908024 -1.412304 -1.920855

In [41]:
# delete a column
df.drop("new", axis=1, inplace=True)
df

          w         x         y         z
a  0.496714 -0.138264  0.647689  1.523030
b -0.234153 -0.234137  1.579213  0.767435
c -0.469474  0.542560 -0.463418 -0.465730
d  0.241962 -1.913280 -1.724918 -0.562288
e -1.012831  0.314247 -0.908024 -1.412304

In [42]:
df.drop('a', inplace=True, axis=0)
df

          w         x         y         z
b -0.234153 -0.234137  1.579213  0.767435
c -0.469474  0.542560 -0.463418 -0.465730
d  0.241962 -1.913280 -1.724918 -0.562288
e -1.012831  0.314247 -0.908024 -1.412304

In [ ]:
# locate row by named index
df.loc["b"]

w   -0.234153
x   -0.234137
y    1.579213
z    0.767435
Name: b, dtype: float64

In [47]:
# locate row by numeric index
df.iloc[1]

w   -0.469474
x    0.542560
y   -0.463418
z   -0.465730
Name: c, dtype: float64

In [48]:
# locate multiple rows
df.loc[['b', 'c', 'd']]

          w         x         y         z
b -0.234153 -0.234137  1.579213  0.767435
c -0.469474  0.542560 -0.463418 -0.465730
d  0.241962 -1.913280 -1.724918 -0.562288

In [51]:
# select specific rows and columns
df.loc[['b', 'c'], ['y', 'z']]

          y         z
b  1.579213  0.767435
c -0.463418 -0.465730