In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)
arr = np.random.randn(5,4)
arr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [3]:
rows = ['a', 'b', 'c', 'd', 'e']
columns = ['w', 'x', 'y', 'z']

In [5]:
df = pd.DataFrame(data=arr, index=rows, columns=columns)
df

          w         x         y         z
a  0.496714 -0.138264  0.647689  1.523030
b -0.234153 -0.234137  1.579213  0.767435
c -0.469474  0.542560 -0.463418 -0.465730
d  0.241962 -1.913280 -1.724918 -0.562288
e -1.012831  0.314247 -0.908024 -1.412304

## Conditional Filters

In [11]:
bool_df = df > 0
bool_df

       w      x      y      z
a   True  False   True   True
b  False  False   True   True
c  False   True  False  False
d   True  False  False  False
e  False   True  False  False

In [10]:
df[bool_df]

          w         x         y         z
a  0.496714       NaN  0.647689  1.523030
b       NaN       NaN  1.579213  0.767435
c       NaN  0.542560       NaN       NaN
d  0.241962       NaN       NaN       NaN
e       NaN  0.314247       NaN       NaN

In [ ]:
# select rows with only values greater than zero in the column 'w'
df[df['w'] > 0]

          w         x         y         z
a  0.496714 -0.138264  0.647689  1.523030
d  0.241962 -1.913280 -1.724918 -0.562288